export const boardgameList = [
  {
    name: "Scoville",
    price: 40,
    status: "available",
    releaseDate: "2014",
    image:
      "https://cf.geekdo-images.com/strK8aDLCB5KuqU3zirUOg__itemrep/img/n0G8YP4A_mgxk5ru1RjowDCPHgQ=/fit-in/246x300/filters:strip_icc()/pic1903464.jpg",
    bggLink: "https://boardgamegeek.com/boardgame/145659/scoville",
    isExpansion: false,
  },
  {
    name: "The Prince of Florence",
    price: 30,
    status: "available",
    releaseDate: "2000",
    image:
      "https://cf.geekdo-images.com/W7IEIU8dZkxD4I6_S9sNJw__imagepage/img/-S9uYHXxNlwytPxhmX4o6cLgifI=/fit-in/900x600/filters:no_upscale():strip_icc()/pic18390.jpg",
    bggLink: "https://boardgamegeek.com/boardgame/555/princes-florence",
    isExpansion: false,
  },
  {
    name: "Castle Panic: The Wizard's Tower",
    price: 20,
    status: "pending",
    releaseDate: "2011",
    image:
      "https://cf.geekdo-images.com/qXmqWZrcjtbRgSeD3NSG5w__imagepage/img/4OU7xd-y2F3iUaHJSEdo88MIR_Y=/fit-in/900x600/filters:no_upscale():strip_icc()/pic1063887.jpg",
    bggLink: "https://boardgamegeek.com/boardgame/104590/castle-panic-wizards-tower",
    isExpansion: true,
    parent: "Castle Panic",
  },
  {
    name: "Mission Red Planet (NIS)",
    price: 45,
    status: "sold",
    releaseDate: "2015",
    image:
      "https://cf.geekdo-images.com/qMUyGstRWieYOyTVA1vsNQ__itemrep/img/gLigWl9nzmQrIbXCFomcaiEx_uM=/fit-in/246x300/filters:strip_icc()/pic2499748.jpg",
    bggLink: "https://boardgamegeek.com/boardgame/176920/mission-red-planet-second-edition",
    isExpansion: false,
  },
  {
    name: "Troyes: The Ladies of Troyes",
    price: 35,
    status: "pending",
    releaseDate: "2012",
    image:
      "https://cf.geekdo-images.com/UDQFqOy1y3UMKFNg4lywuQ__itemrep/img/HaExBNTYAYLPIVLRs-apEshXAqk=/fit-in/246x300/filters:strip_icc()/pic1450377.jpg",
    bggLink: "https://boardgamegeek.com/boardgame/127061/troyes-ladies-troyes",
    isExpansion: true,
    parent: "Troyes",
  },
  {
    name: "Hamburgum",
    price: 30,
    status: "pending",
    releaseDate: "2015",
    image:
      "https://cf.geekdo-images.com/cl4IPnlurFyQ1rNdFCyQkg__itemrep/img/jDP3TwPi3pEwSINN5pKQBBFXi5Q=/fit-in/246x300/filters:strip_icc()/pic260141.jpg",
    bggLink: "https://boardgamegeek.com/boardgame/30381/hamburgum",
    isExpansion: false,
  },
  {
    name: "Ghost Stories: White Moon",
    price: 35,
    status: "available",
    releaseDate: "2009",
    image:
      "https://cf.geekdo-images.com/lqbf-ZuJMkzQaIq6qTn7rA__itemrep/img/uv0KlxXoAQnosKXueNuCRa5atF8=/fit-in/246x300/filters:strip_icc()/pic514248.jpg",
    bggLink: "https://boardgamegeek.com/boardgame/47616/ghost-stories-white-moon",
    isExpansion: true,
    parent: "Ghost Stories",
  },
  {
    name: "Carcassonne: Abby & Mayor (NIS)",
    price: 15,
    status: "pending",
    releaseDate: "2007",
    image:
      "https://cf.geekdo-images.com/QGzPcd0qfC4VV4aQNj-Oug__itemrep/img/94D_xgx1ByKQshvpci2TPSxdAF4=/fit-in/246x300/filters:strip_icc()/pic3513934.jpg",
    bggLink: "https://boardgamegeek.com/boardgame/31784/carcassonne-expansion-5-abbey-mayor",
    isExpansion: true,
    parent: "Carcassonne",
  },
  {
    name: "Carcassonne: Under the Big Top (NIS)",
    price: 15,
    status: "pending",
    releaseDate: "2017",
    image:
      "https://cf.geekdo-images.com/oplINqnlDF2eAAA9m4VSqw__itemrep/img/_9Wd94nN6E1wlCNq0aBVYivw3Po=/fit-in/246x300/filters:strip_icc()/pic3539658.jpg",
    bggLink: "https://boardgamegeek.com/boardgame/217006/carcassonne-expansion-10-under-big-top",
    isExpansion: true,
    parent: "Carcassonne",
  },
  {
    name: "Carcassonne: Hills & Sheep (NIS)",
    price: 15,
    status: "pending",
    releaseDate: "2014",
    image:
      "https://cf.geekdo-images.com/03yF-UoNhPqnBLg4zPzfLA__itemrep/img/-KA-6wKIp51L_xt1zWfcMKQ5uNo=/fit-in/246x300/filters:strip_icc()/pic5389730.png",
    bggLink: "https://boardgamegeek.com/boardgame/153773/carcassonne-expansion-9-hills-sheep",
    isExpansion: true,
    parent: "Carcassonne",
  },
  {
    name: "Carcassonne: Traders & Builders (NIS)",
    price: 15,
    status: "pending",
    releaseDate: "2003",
    image:
      "https://cf.geekdo-images.com/BaBb91gSf9Lu7CA0Pa9sOg__itemrep/img/1atCD77qR8ngVAO17FUBdQgmRbc=/fit-in/246x300/filters:strip_icc()/pic2659946.jpg",
    bggLink: "https://boardgamegeek.com/boardgame/5405/carcassonne-expansion-2-traders-builders",
    isExpansion: true,
    parent: "Carcassonne",
  },
  {
    name: "Power Grid: The Robots",
    price: 10,
    status: "available",
    releaseDate: "2011",
    image:
      "https://cf.geekdo-images.com/4DuQvLs0pH4nVcevop1ncA__itemrep/img/HGu8wgFDCHZ4fHphEk3mWEl1B4A=/fit-in/246x300/filters:strip_icc()/pic1103946.jpg",
    bggLink: "https://boardgamegeek.com/boardgame/108667/power-grid-robots",
    isExpansion: false,
    parent: "Power Grid",
  },
  {
    name: "Tribond",
    price: 5,
    status: "available",
    releaseDate: "1989",
    image: "http://cdn.shopify.com/s/files/1/0260/9361/7198/products/tribond.jpg?v=1615922729",
    bggLink: "https://boardgamegeek.com/boardgame/1962/tribond",
    isExpansion: false,
    parent: "",
  },
  {
    name: "Risk: The Game of Global Domination Collectors Tin",
    price: 35,
    status: "available",
    releaseDate: "2014",
    image: "https://m.media-amazon.com/images/I/51LnBlt71pL._AC_.jpg",
    bggLink: "https://boardgamegeek.com/boardgame/181/risk",
    isExpansion: false,
    parent: "",
  },
  {
    name: "Barony",
    price: 45,
    status: "available",
    releaseDate: "2015",
    image:
      "https://cf.geekdo-images.com/khWmetTHOuTGGluS0LNrfA__itemrep/img/9cM_yJEQZxQ3ygtnl-OTVcLgciA=/fit-in/246x300/filters:strip_icc()/pic2414579.jpg",
    bggLink: "https://boardgamegeek.com/boardgame/167513/barony",
    isExpansion: false,
    parent: "",
  },
  {
    name: "Lords of Hellas",
    price: 90,
    status: "available",
    releaseDate: "2018",
    image:
      "https://cf.geekdo-images.com/iOqSO4vRZFp4MqEKXDXEIw__itemrep/img/uluvq4kOh8Tn9Wn2FChQIpqNetw=/fit-in/246x300/filters:strip_icc()/pic3592207.jpg",
    bggLink: "https://boardgamegeek.com/boardgame/222509/lords-hellas",
    isExpansion: false,
    parent: "",
  },
  {
    name: "Alchemists",
    price: 45,
    status: "available",
    releaseDate: "2014",
    image:
      "https://cf.geekdo-images.com/ztNshEv3Fsm46HCJaEOFPw__itemrep/img/fgFxHXp815uaLr-wVObbguDdjfI=/fit-in/246x300/filters:strip_icc()/pic2241156.png",
    bggLink: "https://boardgamegeek.com/boardgame/161970/alchemists",
    isExpansion: false,
    parent: "",
  },
  {
    name: "Cry Havoc (NIS)",
    price: 45,
    status: "available",
    releaseDate: "2016",
    image:
      "https://cf.geekdo-images.com/OaKLFUgTVdUYvGxLT5QjsQ__itemrep/img/jzj-u8F9jqwB4AxoENc3WufsIn8=/fit-in/246x300/filters:strip_icc()/pic3090929.jpg",
    bggLink: "https://boardgamegeek.com/boardgame/192457/cry-havoc",
    isExpansion: false,
    parent: "",
  },
  {
    name: "Haspelknecht",
    price: 35,
    status: "available",
    releaseDate: "2015",
    image:
      "https://cf.geekdo-images.com/fulMbj3UT2AzhW2uLB-pOg__itemrep/img/GB0DuPRPsPUGa8OdGY0jsxVW6_0=/fit-in/246x300/filters:strip_icc()/pic3070755.jpg",
    bggLink: "https://boardgamegeek.com/boardgame/169794/haspelknecht-story-early-coal-mining",
    isExpansion: false,
    parent: "",
  },
  {
    name: "Jorvik (NIS)",
    price: 30,
    status: "available",
    releaseDate: "",
    image:
      "https://cf.geekdo-images.com/QJfPYxUYyPD1pUy4rOLVfA__itemrep/img/C1ANQXjrVC4rjnvldb3uN48O90g=/fit-in/246x300/filters:strip_icc()/pic3144425.jpg",
    bggLink: "https://boardgamegeek.com/boardgame/193739/jorvik",
    isExpansion: false,
    parent: "",
  },
  {
    name: "Tigris and Euphrates",
    price: 50,
    status: "sold",
    releaseDate: "1997",
    image:
      "https://cf.geekdo-images.com/soAzNVWglCdVBacNjoCTJw__itemrep/img/y9QPelut6bx9GapoVqea8GqtKXQ=/fit-in/246x300/filters:strip_icc()/pic2338267.jpg",
    bggLink: "https://boardgamegeek.com/boardgame/42/tigris-euphrates",
    isExpansion: false,
    parent: "",
  },
  {
    name: "Luna",
    price: 50,
    status: "sold",
    releaseDate: "2010",
    image:
      "https://cf.geekdo-images.com/dMiOhOeyCnTkaGObP_VARg__thumb/img/OPvyAdEonMPNU2B-uUhEBCuFgcc=/fit-in/200x150/filters:strip_icc()/pic1384629.jpg",
    bggLink: "https://boardgamegeek.com/boardgame/70512/luna",
    isExpansion: false,
    parent: "",
  },
  {
    name: "Isle of Skye",
    price: 25,
    status: "available",
    releaseDate: "2015",
    image:
      "https://cf.geekdo-images.com/GCxsnITFBO1pNXiBYkq_qA__itemrep/img/C8fT68XmBkzWDWoC_wh4WeIpEJg=/fit-in/246x300/filters:strip_icc()/pic2524838.jpg",
    bggLink: "https://boardgamegeek.com/boardgame/176494/isle-skye-chieftain-king",
    isExpansion: false,
    parent: "",
  },
  {
    name: "Otys",
    price: 30,
    status: "available",
    releaseDate: "2017",
    image:
      "https://cf.geekdo-images.com/s6AjwCWQfx_QMwQu1GjDlA__itemrep/img/CYP_cqAUbHyOD9Bb9Q76u_0DtB0=/fit-in/246x300/filters:strip_icc()/pic3668630.jpg",
    bggLink: "https://boardgamegeek.com/boardgame/222542/otys",
    isExpansion: false,
    parent: "",
  },
];
